spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/statistics
    username: postgres
    password: postgres
  liquibase:
    changeLog: classpath:liquibase/db.changelog-master.xml
    enabled: true
